In [1]:
import numpy as np

# Random seed for reproducibility
np.random.seed(42)

# Inputs (200 examples, 2 features each)
X = np.random.rand(200, 2).astype(np.float32)  # values between 0 and 1

# True relationship + small noise
true_w = np.array([3, 2], dtype=np.float32)    # weights
true_b = 5.0                                   # bias
noise = np.random.randn(200, 1).astype(np.float32) * 0.1

# Targets
y = (X @ true_w.reshape(-1, 1) + true_b + noise).astype(np.float32)


In [2]:
print(X.shape)  # (4, 2)
print(y.shape)  # (4, 1)


(200, 2)
(200, 1)


In [3]:
weights = np.zeros((X.shape[1], 1), dtype=np.float32)  # (2,1)
bias    = np.zeros((1,),            dtype=np.float32)  # (1,)


In [4]:
import numpy as np

# Pretend this is your model output before adding bias
out = np.array([[10],
                [20],
                [30],
                [40]], dtype=np.float32)  # shape (4,1)

# Bias with shape (1,)
bias = np.array([5], dtype=np.float32)    # shape (1,)

print("out shape:", out.shape)   # (4,1)
print("bias shape:", bias.shape) # (1,)

# Add bias
result = out + bias

print(result)



out shape: (4, 1)
bias shape: (1,)
[[15.]
 [25.]
 [35.]
 [45.]]


In [5]:
def forward(X):
    return np.dot(X, weights) + bias


In [6]:
def MSE(self, y_pred, y_true):
    return np.mean((y_pred - y_true) ** 2)

In [7]:
def gradient_mse(X, y_pred, y_true):
    e = y_pred - y_true              # (n,) shape
    n = X.shape[0]                    # number of samples
    grad_W = (2 / n) * X.T.dot(e)     # shape (features,)
    grad_b = (2 / n) * np.sum(e)      # scalar
    return grad_W, grad_b


In [17]:
EPOCHS = 5000
LEARNING_RATE = 0.01

for epoch in range(EPOCHS):
    y_pred = forward(X)
    loss = MSE(X, y_pred, y)
    grad_W, grad_b = gradient_mse(X, y_pred, y)

    weights -= LEARNING_RATE * grad_W
    bias    -= LEARNING_RATE * grad_b

    print(f"Epoch {epoch+1}, Loss: {loss}")





Epoch 1, Loss: 0.022818593308329582
Epoch 2, Loss: 0.02278698980808258
Epoch 3, Loss: 0.02275547944009304
Epoch 4, Loss: 0.02272404171526432
Epoch 5, Loss: 0.022692671045660973
Epoch 6, Loss: 0.022661373019218445
Epoch 7, Loss: 0.022630156949162483
Epoch 8, Loss: 0.022599009796977043
Epoch 9, Loss: 0.022567955777049065
Epoch 10, Loss: 0.02253696136176586
Epoch 11, Loss: 0.022506041452288628
Epoch 12, Loss: 0.022475192323327065
Epoch 13, Loss: 0.022444428876042366
Epoch 14, Loss: 0.02241373620927334
Epoch 15, Loss: 0.02238311804831028
Epoch 16, Loss: 0.022352570667862892
Epoch 17, Loss: 0.022322094067931175
Epoch 18, Loss: 0.02229168824851513
Epoch 19, Loss: 0.022261371836066246
Epoch 20, Loss: 0.022231116890907288
Epoch 21, Loss: 0.02220095694065094
Epoch 22, Loss: 0.022170843556523323
Epoch 23, Loss: 0.02214081771671772
Epoch 24, Loss: 0.022110851481556892
Epoch 25, Loss: 0.02208096534013748
Epoch 26, Loss: 0.022051166743040085
Epoch 27, Loss: 0.022021420300006866
Epoch 28, Loss: 0.02

In [18]:
bias

array([5.0090885], dtype=float32)

In [19]:
weights

array([[2.989855 ],
       [1.9910078]], dtype=float32)